# Use postgres/example user/password credentials
version: "3.1"
name: craftfinal
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
